services:

  # Haven Nostr Relay
  haven_relay:
    image: letdown2491/haven-relay:latest
    container_name: haven_relay
    restart: unless-stopped
    ports:
      - "3355:3355"
    volumes:
      - ${APP_DATA_DIR}/config:/haven-config
      - ${APP_DATA_DIR}/blossom:/haven/blossom
      - ${APP_DATA_DIR}/db:/haven/db
    env_file:
      - ${APP_DATA_DIR}/config/.env
    networks:
      - haven-kit_haven_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3355"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Configuration UI
  config_ui:
    image: letdown2491/haven-config-ui:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ${APP_DATA_DIR}/config:/haven-config
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /
    env_file:
      - ${APP_DATA_DIR}/config/.env
    environment:
      - DOCKER_SOCK=/var/run/docker.sock
      - APP_DATA_DIR=${PWD}/data
      - RELAY_CONTAINER_NAME=haven_relay
      - RELAY_IMAGE=letdown2491/haven-relay:latest
      - TZ=UTC
    depends_on:
      - haven_relay
    networks:
      - haven-kit_haven_network

networks:
  haven-kit_haven_network:
    name: haven-kit_haven_network
    driver: bridge
